name: agent
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - ase=3.23.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blinker=1.6.2=py311hecd8cb5_0
  - brotli=1.0.9=h6c40b1e_8
  - brotli-bin=1.0.9=h6c40b1e_8
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2024.8.30=h8857fd0_0
  - click=8.1.7=py311hecd8cb5_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311ha357a0b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.5=py311hbafa61a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - elpa=2021.11.001=mpi_openmpi_hcd5f4de_3
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h292e606_110
  - flask=3.0.3=py311hecd8cb5_0
  - fonttools=4.51.0=py311h6c40b1e_0
  - freetype=2.12.1=hd8bbffd_0
  - hdf5=1.14.1=mpi_openmpi_h01be5f8_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.27.0=pyh707e725_0
  - itsdangerous=2.2.0=py311hecd8cb5_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h6eed73b_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=h428f121_1
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libaec=1.1.3=h73e2aa4_0
  - libblas=3.9.0=22_osx64_openblas
  - libbrotlicommon=1.0.9=h6c40b1e_8
  - libbrotlidec=1.0.9=h6c40b1e_8
  - libbrotlienc=1.0.9=h6c40b1e_8
  - libcblas=3.9.0=22_osx64_openblas
  - libcurl=8.9.1=h3a17b82_0
  - libcxx=18.1.8=hd876a4e_6
  - libdeflate=1.17=hb664fd8_1
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - liblapack=3.9.0=22_osx64_openblas
  - liblapacke=3.9.0=22_osx64_openblas
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.27=openmp_h8869122_1
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.11.0=hf20ceda_0
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - libzlib=1.2.13=h87427d6_6
  - llvm-openmp=18.1.8=h15ab845_1
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=2.1.3=py311h6c40b1e_0
  - matplotlib-base=3.8.4=py311h41a4f6b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpi=1.0=openmpi
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py311h91b6869_0
  - numpy-base=1.26.4=py311hb3ec012_0
  - openjpeg=2.5.2=hbf2204d_0
  - openmpi=4.1.6=h7406208_101
  - openssl=3.3.1=hd23fc13_3
  - packaging=24.1=py311hecd8cb5_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py311h46256e1_0
  - pip=24.2=py311hecd8cb5_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311h72ae277_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py311hecd8cb5_0
  - python=3.11.9=hf27a42d_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python_abi=3.11=2_cp311
  - pyzmq=26.2.0=py311h95f92fe_0
  - qe=7.2=hea519da_2
  - readline=8.2=hca72f7f_0
  - scalapack=2.2.0=h208a4c8_1
  - scipy=1.13.1=py311hedc7b93_0
  - setuptools=72.1.0=py311hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h4d00af3_0
  - tornado=6.4.1=py311h3336109_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py311h6c40b1e_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=py311hecd8cb5_0
  - wheel=0.43.0=py311hecd8cb5_0
  - xz=5.4.6=h6c40b1e_1
  - zeromq=4.3.5=h93d8f39_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h87427d6_6
  - zstd=1.5.5=hc035e20_2
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==24.2.0
      - bcrypt==4.2.0
      - boto3==1.35.10
      - botocore==1.35.10
      - certifi==2024.8.30
      - cffi==1.17.0
      - charset-normalizer==3.3.2
      - cryptography==43.0.0
      - defusedxml==0.7.1
      - distro==1.9.0
      - dnspython==2.6.1
      - emmet-core==0.84.2rc6
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - idna==3.8
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - langchain==0.2.15
      - langchain-core==0.2.37
      - langchain-text-splitters==0.2.2
      - langgraph==0.2.15
      - langgraph-checkpoint==1.0.8
      - langsmith==0.1.108
      - latexcodec==3.0.0
      - maggma==0.69.3
      - moltemplate==2.20.20
      - mongomock==4.1.2
      - monty==2024.7.30
      - mp-api==0.42.1
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - networkx==3.3
      - orjson==3.10.7
      - palettable==3.3.3
      - pandas==2.2.2
      - paramiko==3.4.1
      - plotly==5.24.0
      - pybtex==0.24.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydantic-settings==2.4.0
      - pydash==8.0.3
      - pymatgen==2024.8.9
      - pymongo==4.8.0
      - pynacl==1.5.0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.10.2
      - sentinels==1.0.0
      - smart-open==7.0.4
      - sniffio==1.3.1
      - spglib==2.5.0
      - sqlalchemy==2.0.32
      - sshtunnel==0.4.0
      - sympy==1.13.2
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tokenizers==0.20.0
      - tqdm==4.66.5
      - tzdata==2024.1
      - uncertainties==3.2.2
      - urllib3==2.2.2
      - wrapt==1.16.0
      - yarl==1.9.6
