## Environment variables
OLLAMA_BASE_URL: "http://localhost:11434"
OLLAMA_MODEL: "llama3.1"

# Pseudo potential path
PSEUDO_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/all_lda_pbe_UPF'
# PSEUDO_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/sssp'

# Working directory
# WORKING_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/LDAProdNoReflecout'
WORKING_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/BEEFtry3out'

SAVE_DIALOGUE: 'True'
