## Environment variables
OLLAMA_BASE_URL: "http://localhost:11434"
OLLAMA_MODEL: "qwen3:latest"

# Pseudo potential path
PSEUDO_DIR: 'resources/all_lda_pbe_UPF'

# Working directory
WORKING_DIR: 'output/BEEFtry3out'

SAVE_DIALOGUE: true
